"""Create expenses table

Revision ID: 7f044b434387
Revises: 
Create Date: 2025-10-03 10:54:29.801915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f044b434387'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('expense_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='expense'
    )
    op.create_index(op.f('ix_expense_expenses_cost'), 'expenses', ['cost'], unique=False, schema='expense')
    op.create_index(op.f('ix_expense_expenses_expense_type'), 'expenses', ['expense_type'], unique=False, schema='expense')
    op.create_index(op.f('ix_expense_expenses_location'), 'expenses', ['location'], unique=False, schema='expense')
    op.create_index(op.f('ix_expense_expenses_owner_id'), 'expenses', ['owner_id'], unique=False, schema='expense')
    op.create_index(op.f('ix_expense_expenses_provider_id'), 'expenses', ['provider_id'], unique=False, schema='expense')
    op.create_index(op.f('ix_expense_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False, schema='expense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_expenses_vehicle_id'), table_name='expenses', schema='expense')
    op.drop_index(op.f('ix_expense_expenses_provider_id'), table_name='expenses', schema='expense')
    op.drop_index(op.f('ix_expense_expenses_owner_id'), table_name='expenses', schema='expense')
    op.drop_index(op.f('ix_expense_expenses_location'), table_name='expenses', schema='expense')
    op.drop_index(op.f('ix_expense_expenses_expense_type'), table_name='expenses', schema='expense')
    op.drop_index(op.f('ix_expense_expenses_cost'), table_name='expenses', schema='expense')
    op.drop_table('expenses', schema='expense')
    # ### end Alembic commands ###
